name: Build wheels

on: [push, pull_request]

# Default parameters for all builds
env:
  ARTIFACT_RETENTION: ${{ github.ref == 'refs/heads/master' && '30' || '7' }}

jobs:
  cpython-linux-x86_64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        cibw_archs: ["x86_64"]
        manylinux_image: ["manylinux2010"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BEFORE_BUILD: pip install cython
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_archs }}
          CIBW_BUILD: "cp38-* cp39-*"
          CIBW_SKIP: pp*
          #cp36-* cp37-* 
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: networkit-cp36-${{ matrix.manylinux_image}}-${{ matrix.cibw_archs }}.whl
      #     path: ./wheelhouse/*cp36*.whl
      #     retention-days: ${{ env.ARTIFACT_RETENTION }}
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: networkit-cp37-${{ matrix.manylinux_image}}-${{ matrix.cibw_archs }}.whl
      #     path: ./wheelhouse/*cp37*.whl
      #     retention-days: ${{ env.ARTIFACT_RETENTION }}
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: networkit-cp38-${{ matrix.manylinux_image}}-${{ matrix.cibw_archs }}.whl
      #     path: ./wheelhouse/*cp38*.whl
      #     retention-days: ${{ env.ARTIFACT_RETENTION }}
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: networkit-cp39-${{ matrix.manylinux_image}}-${{ matrix.cibw_archs }}.whl
      #     path: ./wheelhouse/*cp39*.whl
      #     retention-days: ${{ env.ARTIFACT_RETENTION }}
      # - name: Upload to TestPyPI
      #   run: |
      #     pip install twine 
      #     python3 -m twine upload --verbose --skip-existing --repository testpypi ./wheelhouse/*
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}

  # cpython-linux-aarch64:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-20.04]
  #       cibw_archs: ["aarch64"]
  #       manylinux_image: ["manylinux2014"]
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #       with:
  #         platforms: all
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #     - uses: actions/setup-python@v2
  #       name: Install Python
  #       with:
  #         python-version: '3.9'
  #     - name: Build wheels
  #       uses: pypa/cibuildwheel@v2.1.1
  #       env:
  #         CIBW_BEFORE_BUILD: pip install cython
  #         CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
  #         CIBW_ARCHS_LINUX: ${{ matrix.cibw_archs }}
  #         CIBW_BUILD: "cp39-*"
  #         CIBW_SKIP: pp*
      
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: networkit-cp39-${{ matrix.manylinux_image}}-${{ matrix.cibw_archs }}.whl
  #         path: ./wheelhouse/*cp39*.whl
  #         retention-days: ${{ env.ARTIFACT_RETENTION }}
  #     - name: Upload to TestPyPI
  #       run: |
  #         pip install twine 
  #         python3 -m twine upload --verbose --skip-existing --repository testpypi ./wheelhouse/*
  #       env:
  #         TWINE_USERNAME: __token__
  #         TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}

  cpython-macos-x86_64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        cibw_archs: ["x86_64"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BEFORE_BUILD: 
            pip install cython &&
            brew install libomp ninja
          CIBW_ARCHS_MACOS: ${{ matrix.cibw_archs }}
          CIBW_BUILD: "cp39-*"
          CIBW_SKIP: pp*
          # cp36-* cp37-* cp38-*
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: networkit-cp36-macos-${{ matrix.cibw_archs }}.whl
      #     path: ./wheelhouse/*cp36*.whl
      #     retention-days: ${{ env.ARTIFACT_RETENTION }}
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: networkit-cp37-macos-${{ matrix.cibw_archs }}.whl
      #     path: ./wheelhouse/*cp37*.whl
      #     retention-days: ${{ env.ARTIFACT_RETENTION }}
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: networkit-cp38-macos-${{ matrix.cibw_archs }}.whl
      #     path: ./wheelhouse/*cp38*.whl
      #     retention-days: ${{ env.ARTIFACT_RETENTION }}
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: networkit-cp39-macos-${{ matrix.cibw_archs }}.whl
      #     path: ./wheelhouse/*cp39*.whl
      #     retention-days: ${{ env.ARTIFACT_RETENTION }}
      # - name: Upload to TestPyPI
      #   run: |
      #     pip install twine 
      #     python3 -m twine upload --verbose --skip-existing --repository testpypi ./wheelhouse/*
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}

  # cpython-macos-arm64:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macos-latest]
  #       cibw_archs: ["arm64"]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #     - uses: actions/setup-python@v2
  #       name: Install Python
  #       with:
  #         python-version: '3.9'
  #     - name: Build wheels
  #       uses: pypa/cibuildwheel@v2.1.1
  #       env:
  #         CIBW_BEFORE_BUILD: 
  #           pip install cython &&
  #           brew install libomp ninja &&
  #           pip install --pre -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy
  #         CIBW_ENVIRONMENT: CXX=c++ NETWORKIT_OSX_CROSSBUILD=ON
  #         CIBW_ARCHS_MACOS: ${{ matrix.cibw_archs }}
  #         CIBW_BUILD: "cp39-*"
  #         CIBW_SKIP: pp*
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: networkit-cp39-macos-${{ matrix.cibw_archs }}.whl
  #         path: ./wheelhouse/*cp39*.whl
  #         retention-days: ${{ env.ARTIFACT_RETENTION }}
  #     - name: Upload to TestPyPI
  #       run: |
  #         pip install twine 
  #         python3 -m twine upload --verbose --skip-existing --repository testpypi ./wheelhouse/*
  #       env:
  #         TWINE_USERNAME: __token__
  #         TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}

  # cpython-windows:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [windows-latest]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #     - name: Setup devCmd (vstools)
  #       uses: ilammy/msvc-dev-cmd@v1
  #     - uses: actions/setup-python@v2
  #       name: Install Python
  #       with:
  #         python-version: '3.9'
  #     - name: Build wheels
  #       uses: pypa/cibuildwheel@v2.1.2
  #       env:
  #         CIBW_BEFORE_BUILD: pip install cython ipython
  #         CIBW_ARCHS: "AMD64"
  #         CIBW_BUILD: "cp39-*"
  #         CIBW_SKIP: pp*
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: networkit-cp39-win-amd64.whl
  #         path: ./wheelhouse/*cp39*.whl
  #         retention-days: ${{ env.ARTIFACT_RETENTION }}
  #     - name: Upload to TestPyPI
  #       run: |
  #         pip install twine 
  #         python3 -m twine upload --verbose --skip-existing --repository testpypi ./wheelhouse/*
  #       env:
  #         TWINE_USERNAME: __token__
  #         TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}

  source-distribution:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'
      - name: Create sdist source
        run: |
          pip install cython
          python3 setup.py build_ext
          python3 setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*networkit*.tar.gz

  upload-packages:
    runs-on: ubuntu-20.04
    needs: [cpython-macos-x86_64, cpython-linux-x86_64, source-distribution]
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ./dist
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'
      - name: Upload to TestPyPI
        run: |
          pip install twine 
          python3 -m twine upload --verbose --skip-existing --repository testpypi ./dist/artifact/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}